import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'

import NavMenu from './NavMenu'

const nunito = Nunito({
    weight: '400',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={nunito.className}>
                <NavMenu />
                <main>{children}</main>
            </body>
        </html>
    )
}
